### ISSUE TITLE
v2.0.4 is broken - require is not a function

### ISSUE THREAD

**Issue by nirtayeb** [erisanolasheni/custom-env#31]
Using 2.0.2 this code is working:
```
const customEnv = require('custom-env');
customEnv.env(process.env.NODE_ENV, 'env');
```

But after upgrading to 2.0.4 I get this error message, I downgraded for now.

```
/app/node_modules/custom-env/lib/main.js:166
            require('dotenv-expand')(require('dotenv').config(dotenvobj));
                                    ^
TypeError: require(...) is not a function
    at main.loadDotEnvConfig (/app/node_modules/custom-env/lib/main.js:166:37)
    at main.loadCustomDotEnv (/app/node_modules/custom-env/lib/main.js:183:14)
    at new main (/app/node_modules/custom-env/lib/main.js:187:10)
    at Object.env (/app/node_modules/custom-env/lib/main.js:196:21)
    at Object.<anonymous> (/app/dist/app/app.js:5:11)
    at Module._compile (node:internal/modules/cjs/loader:1368:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
    at Module.load (node:internal/modules/cjs/loader:1205:32)
    at Module._load (node:internal/modules/cjs/loader:1021:12)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
Node.js v21.7.3
```

**Comment by erisanolasheni** [comment]
Hello, @nirtayeb sorry for this error, and thanks for bringing this up. I just checked now and see. This is caused by a bump in the `dotenv-expand` version, I have gracefully reverted to the last know `dotenv-expand` version and everything is good now with `v2.0.5` also now available here: https://github.com/erisanolasheni/custom-env/releases/tag/v2.0.5 and here: https://www.npmjs.com/package/custom-env/v/2.0.5.
Because I am quite busy now and no one is sponsoring this project for now, I will have to make more time in the nearest future to work on the actually fix for a greater `dotenv-expand` version, however you can now use the `v2.0.5` without any issues.

Of course you are also free to contribute! I will be happy. Thank you.
